from ctypes import Structure
from pyjab.common.types import JOBJECT64 as JOBJECT64
from pyjab.config import MAX_ACTIONS_TO_DO as MAX_ACTIONS_TO_DO, MAX_ACTION_INFO as MAX_ACTION_INFO, MAX_KEY_BINDINGS as MAX_KEY_BINDINGS, MAX_RELATIONS as MAX_RELATIONS, MAX_RELATION_TARGETS as MAX_RELATION_TARGETS, MAX_STRING_SIZE as MAX_STRING_SIZE, MAX_VISIBLE_CHILDREN as MAX_VISIBLE_CHILDREN, SHORT_STRING_SIZE as SHORT_STRING_SIZE

class AccessBridgeVersionInfo(Structure): ...
class AccessibleContextInfo(Structure): ...
class AccessibleTextInfo(Structure): ...
class AccessibleTextItemsInfo(Structure): ...
class AccessibleTextSelectionInfo(Structure): ...
class AccessibleTextRectInfo(Structure): ...
class AccessibleTextAttributesInfo(Structure): ...
class AccessibleRelationInfo(Structure): ...
class AccessibleRelationSetInfo(Structure): ...
class AccessibleActionInfo(Structure): ...
class AccessibleActions(Structure): ...
class AccessibleActionsToDo(Structure): ...
class AccessibleTableInfo(Structure): ...
class AccessibleTableCellInfo(Structure): ...
class AccessibleKeyBindingInfo(Structure): ...
class AccessibleKeyBindings(Structure): ...
class VisibleChildrenInfo(Structure): ...
