from _typeshed import Incomplete

MAX_STRING_SIZE: int
SHORT_STRING_SIZE: int
MAX_KEY_BINDINGS: int
MAX_RELATION_TARGETS: int
MAX_RELATIONS: int
MAX_ACTION_INFO: int
MAX_ACTIONS_TO_DO: int
MAX_VISIBLE_CHILDREN: int
TIMEOUT: int
WAB_DLL: str
JDK_BRIDGE_DLL: Incomplete
JRE_BRIDGE_DLL: Incomplete
JAB_BRIDGE_DLL: Incomplete
A11Y_PROPS_PATH: Incomplete
A11Y_PROPS_CONTENT: str
