import types
from _typeshed import Incomplete
from ctypes import CDLL, c_long
from ctypes.wintypes import HWND as HWND
from pathlib import Path
from pyjab.accessibleinfo import AccessBridgeVersionInfo as AccessBridgeVersionInfo
from pyjab.common.actorscheduler import ActorScheduler as ActorScheduler
from pyjab.common.by import By as By
from pyjab.common.exceptions import JABException as JABException
from pyjab.common.logger import Logger as Logger
from pyjab.common.service import Service as Service
from pyjab.common.types import JOBJECT64 as JOBJECT64
from pyjab.common.win32utils import Win32Utils as Win32Utils
from pyjab.config import TIMEOUT as TIMEOUT
from pyjab.jabelement import JABElement as JABElement
from pyjab.jabfixedfunc import JABFixedFunc as JABFixedFunc
from typing import Any

class JABDriver:
    win32utils: Incomplete
    file_path: Incomplete
    serv: Incomplete
    logger: Incomplete
    latest_log: Incomplete
    def __init__(self, title: str = '', file_path: Path = None, bridge_dll: str = '', hwnd: HWND = None, vmid: c_long = None, accessible_context: JOBJECT64 = None, timeout: int = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def open_application(self): ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, title: str) -> None: ...
    @property
    def hwnd(self) -> HWND: ...
    @hwnd.setter
    def hwnd(self, hwnd: HWND) -> None: ...
    @property
    def pid(self) -> int: ...
    @pid.setter
    def pid(self, pid: int) -> None: ...
    @property
    def vmid(self) -> c_long: ...
    @vmid.setter
    def vmid(self, vmid: c_long) -> None: ...
    @property
    def accessible_context(self) -> JOBJECT64: ...
    @accessible_context.setter
    def accessible_context(self, accessible_context: JOBJECT64) -> None: ...
    @property
    def bridge(self) -> CDLL: ...
    @bridge.setter
    def bridge(self, bridge: CDLL) -> None: ...
    @property
    def root_element(self) -> JABElement: ...
    @root_element.setter
    def root_element(self, root_element: JABElement) -> None: ...
    def init_jab(self) -> None: ...
    def get_pid_from_hwnd(self): ...
    def get_version_info(self) -> dict[str, str]: ...
    def get_java_window_hwnd(self, title: str) -> HWND | None: ...
    def wait_java_window_by_title(self, title: str, timeout: int = ...) -> HWND: ...
    def find_element_by_name(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_description(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_role(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_states(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_object_depth(self, value: int, visible: bool = False) -> JABElement: ...
    def find_element_by_children_count(self, value: int, visible: bool = False) -> JABElement: ...
    def find_element_by_index_in_parent(self, value: int, visible: bool = False) -> JABElement: ...
    def find_element_by_xpath(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element(self, by: str = ..., value: Any = None, visible: bool = False) -> JABElement: ...
    def find_elements_by_name(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_description(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_role(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_states(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_object_depth(self, value: int, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_children_count(self, value: int, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_index_in_parent(self, value: int, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_xpath(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements(self, by: str = ..., value: str = None, visible: bool = False) -> list[JABElement]: ...
    def maximize_window(self) -> None: ...
    def minimize_window(self) -> None: ...
    def wait_until_element_exist(self, by: str = ..., value: Any = None, timeout: int = ...) -> JABElement: ...
    def get_screenshot_as_file(self, filename) -> None: ...
    def get_screenshot(self): ...
    def set_window_size(self, width, height) -> None: ...
    def set_window_position(self, x, y) -> None: ...
    def get_window_position(self): ...
