from PIL import Image as Image
from _typeshed import Incomplete
from ctypes import CDLL, c_long
from ctypes.wintypes import HWND as HWND
from pyjab.accessibleinfo import AccessibleActions as AccessibleActions, AccessibleActionsToDo as AccessibleActionsToDo, AccessibleContextInfo as AccessibleContextInfo, AccessibleTableCellInfo as AccessibleTableCellInfo, AccessibleTableInfo as AccessibleTableInfo, AccessibleTextInfo as AccessibleTextInfo, VisibleChildrenInfo as VisibleChildrenInfo
from pyjab.common.by import By as By
from pyjab.common.exceptions import JABException as JABException
from pyjab.common.logger import Logger as Logger
from pyjab.common.role import Role as Role
from pyjab.common.states import States as States
from pyjab.common.textreader import TextReader as TextReader
from pyjab.common.types import JOBJECT64 as JOBJECT64, jint as jint
from pyjab.common.win32utils import Win32Utils as Win32Utils
from pyjab.common.xpathparser import XpathParser as XpathParser
from typing import Any

class JABElement:
    int_func_err_msg: str
    win32_utils: Incomplete
    xpath_parser: Incomplete
    logger: Incomplete
    def __init__(self, bridge: CDLL = None, hwnd: HWND = None, vmid: c_long = None, accessible_context: JOBJECT64 = None) -> None: ...
    @property
    def bridge(self) -> CDLL: ...
    @bridge.setter
    def bridge(self, bridge: CDLL) -> None: ...
    @property
    def hwnd(self) -> HWND: ...
    @hwnd.setter
    def hwnd(self, hwnd: HWND) -> None: ...
    @property
    def vmid(self) -> c_long: ...
    @vmid.setter
    def vmid(self, vmid: c_long) -> None: ...
    @property
    def accessible_context(self) -> JOBJECT64: ...
    @accessible_context.setter
    def accessible_context(self, accessible_context: JOBJECT64) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def role(self) -> str: ...
    @property
    def role_en_us(self) -> str: ...
    @property
    def states(self) -> str: ...
    @property
    def states_en_us(self) -> str: ...
    @property
    def object_depth(self) -> int: ...
    @property
    def index_in_parent(self) -> int: ...
    @property
    def children_count(self) -> int: ...
    @property
    def bounds(self) -> dict: ...
    @property
    def accessible_component(self) -> bool: ...
    @property
    def accessible_action(self) -> bool: ...
    @property
    def accessible_selection(self) -> bool: ...
    @property
    def accessible_text(self) -> bool: ...
    @property
    def accessible_interfaces(self) -> bool: ...
    @property
    def text(self) -> str: ...
    @property
    def table(self) -> dict: ...
    def release_jabelement(self, jabelement: JABElement = None) -> None: ...
    def click(self, simulate: bool = False) -> None: ...
    def clear(self, simulate: bool = False, wait_for_text_update: bool = True) -> None: ...
    def scroll(self, to_bottom: bool = True, hold: int = 2) -> None: ...
    def slide(self, to_bottom: bool = True, hold: int = 5) -> None: ...
    def select(self, option: str, simulate: bool = False, wait_for_selection: bool = True) -> None: ...
    def get_selected_element(self) -> JABElement: ...
    def spin(self, option: str = None, increase: bool = True, simulate: bool = False) -> None: ...
    def expand(self, simulate: bool = False) -> None: ...
    def send_text(self, value: str | int, simulate: bool = False, wait_for_text_update: bool = True) -> None: ...
    def is_checked(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def is_visible(self) -> bool: ...
    def is_showing(self) -> bool: ...
    def is_selected(self) -> bool: ...
    def is_editable(self) -> bool: ...
    def find_element_by_name(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_description(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_role(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element_by_states(self, value: list | str, visible: bool = False) -> JABElement: ...
    def find_element_by_object_depth(self, value: int, visible: bool = False) -> JABElement: ...
    def find_element_by_children_count(self, value: int, visible: bool = False) -> JABElement: ...
    def find_element_by_index_in_parent(self, value: int, visible: bool = False) -> JABElement: ...
    def find_element_by_xpath(self, value: str, visible: bool = False) -> JABElement: ...
    def find_element(self, by: str = ..., value: Any = None, visible: bool = False) -> JABElement: ...
    def find_elements_by_name(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_description(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_role(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_states(self, value: list | str, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_object_depth(self, value: int, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_children_count(self, value: int, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_index_in_parent(self, value: int, visible: bool = False) -> list[JABElement]: ...
    def find_elements_by_xpath(self, value: str, visible: bool = False) -> list[JABElement]: ...
    def find_elements(self, by: str = ..., value: list | str | int = None, visible: bool = False) -> list[JABElement]: ...
    @property
    def size(self) -> dict: ...
    @property
    def location(self) -> dict: ...
    def get_screenshot_as_file(self, filename: str) -> None: ...
    def get_screenshot(self) -> Image: ...
    @property
    def parent(self): ...
    def get_cell(self, row: int, column: int, visible: bool = False) -> JABElement: ...
    def get_element_information(self) -> dict: ...
