from _typeshed import Incomplete
from pyjab.common.logger import Logger as Logger
from pyjab.common.singleton import singleton as singleton

class ActorScheduler:
    actors: Incomplete
    msg_queue: Incomplete
    logger: Incomplete
    def __init__(self) -> None: ...
    def new_actor(self, name, actor) -> None: ...
    def send(self, name, msg) -> None: ...
    def run(self) -> None: ...
