from _typeshed import Incomplete
from pyjab.common.singleton import singleton as singleton

class Logger:
    LOGGER_INFO: Incomplete
    LOGGER_DEBUG: Incomplete
    LOGGER_WARN: Incomplete
    LOGGER_ERROR: Incomplete
    LOGGER_CRITICAL: Incomplete
    FORMAT: str
    log: Incomplete
    def __init__(self, name=None, level=...) -> None: ...
    def info(self, msg, *args, **kwargs) -> None: ...
    def debug(self, msg, *args, **kwargs) -> None: ...
    def warning(self, msg, *args, **kwargs) -> None: ...
    def error(self, msg, *args, **kwargs) -> None: ...
    def critical(self, msg, *args, **kwargs) -> None: ...
