from _typeshed import Incomplete
from ctypes import CDLL
from pyjab.common.logger import Logger as Logger
from pyjab.common.singleton import singleton as singleton
from pyjab.config import A11Y_PROPS_CONTENT as A11Y_PROPS_CONTENT, A11Y_PROPS_PATH as A11Y_PROPS_PATH, JAB_BRIDGE_DLL as JAB_BRIDGE_DLL, JDK_BRIDGE_DLL as JDK_BRIDGE_DLL, JRE_BRIDGE_DLL as JRE_BRIDGE_DLL

class Service:
    logger: Incomplete
    def __init__(self) -> None: ...
    def enable_bridge(self) -> None: ...
    def is_bridge_enabled(self) -> bool: ...
    def init_bridge(self) -> None: ...
    def load_library(self, bridge_dll: str = '') -> CDLL: ...
