from _typeshed import Incomplete
from pyjab.common.logger import Logger as Logger
from pyjab.common.win32utils import Win32Utils as Win32Utils

class ShortcutKeys:
    logger: Incomplete
    win32_utils: Incomplete
    press_hold_release_key: Incomplete
    press_key: Incomplete
    def __init__(self) -> None: ...
    def clear_text(self) -> None: ...
    def paste(self) -> None: ...
    def block_menu(self) -> None: ...
    def clear_block(self) -> None: ...
    def clear_field(self) -> None: ...
    def clear_form(self) -> None: ...
    def clear_record(self) -> None: ...
    def commit(self) -> None: ...
    def count_query(self) -> None: ...
    def delete_record(self) -> None: ...
    def display_error(self) -> None: ...
    def down(self) -> None: ...
    def duplicate_field(self) -> None: ...
    def duplicate_record(self) -> None: ...
    def edit(self) -> None: ...
    def enter_query(self) -> None: ...
    def execute_query(self) -> None: ...
    def insert_record(self) -> None: ...
    def list_of_values(self) -> None: ...
    def list_tab_pages(self) -> None: ...
    def next_block(self) -> None: ...
    def next_field(self) -> None: ...
    def next_primary_key(self) -> None: ...
    def next_record(self) -> None: ...
    def next_set_of_records(self) -> None: ...
    def previous_block(self) -> None: ...
    def previous_field(self) -> None: ...
    def previous_record(self) -> None: ...
    def scroll_down(self) -> None: ...
    def scroll_up(self) -> None: ...
    def show_keys(self) -> None: ...
    def up(self) -> None: ...
    def update_record(self) -> None: ...
