from _typeshed import Incomplete
from ctypes.wintypes import HWND as HWND
from pyjab.common.logger import Logger as Logger
from pyjab.common.singleton import singleton as singleton
from pyjab.config import TIMEOUT as TIMEOUT
from typing import Generator

class Win32Utils:
    stop_event: Incomplete
    other_event: Incomplete
    virtual_key_code: Incomplete
    logger: Incomplete
    def __init__(self) -> None: ...
    def setup_msg_pump(self) -> Generator: ...
    @staticmethod
    def enum_windows() -> dict[HWND, str]: ...
    def get_hwnd_by_title(self, title: str) -> HWND | None: ...
    def get_hwnds_by_title(self, title: str) -> list[HWND]: ...
    @staticmethod
    def get_title_by_hwnd(hwnd: HWND) -> str: ...
    def wait_hwnd_by_title(self, title: str, timeout: int = ...) -> HWND: ...
